-- 코드를 입력하세요
SELECT
    T101.PRDT_CD    AS PRDT_CD,
    SUM(T101.PRC * T102.SAL_AMT) AS SAL_AMT
FROM
(SELECT
    PRODUCT_ID      AS PRDT_ID,
    PRODUCT_CODE    AS PRDT_CD,
    PRICE           AS PRC
FROM PRODUCT) T101
INNER JOIN
(SELECT
    PRODUCT_ID      AS PRDT_ID,
    SALES_AMOUNT    AS SAL_AMT
FROM OFFLINE_SALE) T102
ON T101.PRDT_ID = T102.PRDT_ID
GROUP BY
    T101.PRDT_CD
ORDER BY SAL_AMT DESC, PRDT_CD