SELECT
    T101.PRODUCT_ID             AS PRODUCT_ID
    , T101.PRODUCT_NAME         AS PRODUCT_NAME
    , T102.AMOUNT * T101.PRICE  AS TOTAL_SALE
FROM
(SELECT
    PRODUCT_ID      AS PRODUCT_ID
    , PRODUCT_NAME  AS PRODUCT_NAME
    , PRICE         AS PRICE
FROM FOOD_PRODUCT
) T101
INNER JOIN
(SELECT
    PRODUCT_ID      AS PRODUCT_ID
    , SUM(AMOUNT)   AS AMOUNT
FROM FOOD_ORDER
WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY
    PRODUCT_ID
) T102
ON T101.PRODUCT_ID = T102.PRODUCT_ID
ORDER BY T102.AMOUNT * T101.PRICE DESC, T101.PRODUCT_ID ASC;