SELECT T302.MEMBER_NAME,
        T303.REVIEW_TEXT,
        DATE_FORMAT(T303.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
(SELECT
    T202.CNT,
    T202.MEMBER_ID
FROM
    (SELECT MAX(T101.CNT) AS MAX_CNT
    FROM
        (SELECT  COUNT(1) AS CNT,
                MEMBER_ID AS MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID) T101
    ) T201
INNER JOIN
    (SELECT COUNT(MEMBER_ID) AS CNT,
            MEMBER_ID        AS MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID) T202
ON T201.MAX_CNT = T202.CNT) T301
INNER JOIN
    (SELECT MEMBER_ID, MEMBER_NAME FROM MEMBER_PROFILE) T302
ON T301.MEMBER_ID = T302.MEMBER_ID

INNER JOIN
    (SELECT MEMBER_ID, REVIEW_TEXT, REVIEW_DATE FROM REST_REVIEW) T303
ON T301.MEMBER_ID = T303.MEMBER_ID
ORDER BY REVIEW_DATE, MEMBER_NAME