SELECT
    T101.BOOK_ID
    , T102.AUTHOR_NAME
    , DATE_FORMAT(T101.PUBLISHED_DATE, '%Y-%m-%d')
FROM
(SELECT
    BOOK_ID
    , AUTHOR_ID
    , PUBLISHED_DATE
FROM BOOK
WHERE 1=1
  AND CATEGORY = '경제') T101
LEFT OUTER JOIN
(SELECT
    AUTHOR_ID
    , AUTHOR_NAME
FROM AUTHOR
) T102
ON T101.AUTHOR_ID = T102.AUTHOR_ID
ORDER BY
    T101.PUBLISHED_DATE ASC;